// Generated by dts-bundle-generator v9.5.1

import { HTMLAttributes, ReactElement, ReactNode } from "react";

export type HighlightFn = (code: string, lang: string) => ReactNode[];
export type MathFn = (tex: string, block: boolean) => ReactNode;
export type RawHtmlProp = boolean | Record<string, string[]>;
declare function Markdown({
  children,
  highlight,
  math,
  rawHtml,
  ...props
}: {
  children: string;
  highlight?: HighlightFn;
  math?: MathFn | false;
  rawHtml?: RawHtmlProp;
} & HTMLAttributes<HTMLDivElement>): ReactElement;

export { Markdown as default };

export {};
