// Generated by dts-bundle-generator v9.5.1

import { HTMLAttributes, ReactElement, ReactNode } from "react";

export type RawHtml = Record<string, string[]>;
export declare const allowTags: RawHtml;
export type HighlightFn = (code: string, lang: string) => ReactNode[];
export type MathFn = (tex: string, block: boolean) => ReactNode;
declare function Markdown({
  children,
  highlight,
  math,
  rawHtml,
  ...props
}: {
  children: string;
  highlight?: boolean | HighlightFn;
  math?: boolean | MathFn;
  rawHtml?: boolean | RawHtml;
} & HTMLAttributes<HTMLDivElement>): ReactElement;

export { Markdown as default };

export {};
